[project]
name = "langchain-ollama-chroma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.2",
    "langchain-chroma>=1.0.0",
    "langchain-ollama>=1.0.0",
]
